# Dockerfile with SteamRT3
FROM        registry.gitlab.steamos.cloud/steamrt/sniper/platform:latest-container-runtime-depot
LABEL       author="orl4nd1 @ histeriaservers.com.ar" \
            maintainer="orl4nd1cs@histeriaservers.com.ar" \
            org.opencontainers.image.description="CS2 Pterodactyl Egg Dockerfile forked of Kayruu CS2Lab" \
            org.opencontainers.image.source="https://github.com/ZMatu/CS2-EGG-HISTERIA"

# Prep OS
RUN         mkdir -p /etc/sudoers.d && \
            echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/flatdeb && \
            chmod 0440 /etc/sudoers.d/flatdeb

ENV         DEBIAN_FRONTEND=noninteractive
RUN         apt update && \
            apt install -y iproute2 jq unzip expect rsync && \
            apt-get clean

# Create directories and copy files
RUN         mkdir -p /scripts /utils
COPY        ./scripts/* /scripts/
COPY        ./utils/* /utils/
COPY        ./entrypoint.sh /entrypoint.sh

# Set permissions
RUN         chmod +x /scripts/*.sh && \
            chmod +x /utils/*.sh && \
            chmod +x /entrypoint.sh

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

CMD         [ "/bin/bash", "/entrypoint.sh" ]
